# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ui_advanced_window.ui'
#
# Created: Tue May  2 11:25:21 2017
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(502, 520)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.mantid_browse_characterization_button = QtGui.QPushButton(self.groupBox)
        self.mantid_browse_characterization_button.setMinimumSize(QtCore.QSize(200, 0))
        self.mantid_browse_characterization_button.setObjectName(_fromUtf8("mantid_browse_characterization_button"))
        self.horizontalLayout_5.addWidget(self.mantid_browse_characterization_button)
        self.mantid_characterization_value = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mantid_characterization_value.sizePolicy().hasHeightForWidth())
        self.mantid_characterization_value.setSizePolicy(sizePolicy)
        self.mantid_characterization_value.setObjectName(_fromUtf8("mantid_characterization_value"))
        self.horizontalLayout_5.addWidget(self.mantid_characterization_value)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.mantid_number_of_bins = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mantid_number_of_bins.sizePolicy().hasHeightForWidth())
        self.mantid_number_of_bins.setSizePolicy(sizePolicy)
        self.mantid_number_of_bins.setObjectName(_fromUtf8("mantid_number_of_bins"))
        self.horizontalLayout_4.addWidget(self.mantid_number_of_bins)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_2.addWidget(self.label_23)
        self.ndeg = QtGui.QSpinBox(self.groupBox)
        self.ndeg.setMaximum(2)
        self.ndeg.setProperty("value", 2)
        self.ndeg.setObjectName(_fromUtf8("ndeg"))
        self.horizontalLayout_2.addWidget(self.ndeg)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.q_range_group_box = QtGui.QGroupBox(self.groupBox)
        self.q_range_group_box.setObjectName(_fromUtf8("q_range_group_box"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.q_range_group_box)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.q_range_group_box)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.q_range_min = QtGui.QLineEdit(self.q_range_group_box)
        self.q_range_min.setMinimumSize(QtCore.QSize(80, 0))
        self.q_range_min.setMaximumSize(QtCore.QSize(80, 16777215))
        self.q_range_min.setObjectName(_fromUtf8("q_range_min"))
        self.horizontalLayout.addWidget(self.q_range_min)
        self.label_2 = QtGui.QLabel(self.q_range_group_box)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.q_range_max = QtGui.QLineEdit(self.q_range_group_box)
        self.q_range_max.setMinimumSize(QtCore.QSize(80, 0))
        self.q_range_max.setMaximumSize(QtCore.QSize(80, 16777215))
        self.q_range_max.setObjectName(_fromUtf8("q_range_max"))
        self.horizontalLayout.addWidget(self.q_range_max)
        self.pushButton = QtGui.QPushButton(self.q_range_group_box)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.q_range_group_box)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_3.addWidget(self.label_15)
        self.mantid_min_crop_wavelength = QtGui.QLineEdit(self.groupBox_2)
        self.mantid_min_crop_wavelength.setObjectName(_fromUtf8("mantid_min_crop_wavelength"))
        self.horizontalLayout_3.addWidget(self.mantid_min_crop_wavelength)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_3.addWidget(self.label_16)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_3.addWidget(self.label_14)
        self.mantid_max_crop_wavelength = QtGui.QLineEdit(self.groupBox_2)
        self.mantid_max_crop_wavelength.setObjectName(_fromUtf8("mantid_max_crop_wavelength"))
        self.horizontalLayout_3.addWidget(self.mantid_max_crop_wavelength)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_3.addWidget(self.label_13)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_6.addWidget(self.label_24)
        self.ndeg_2 = QtGui.QSpinBox(self.groupBox_3)
        self.ndeg_2.setMaximum(2)
        self.ndeg_2.setProperty("value", 2)
        self.ndeg_2.setObjectName(_fromUtf8("ndeg_2"))
        self.horizontalLayout_6.addWidget(self.ndeg_2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 502, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Auto Reduction", None))
        self.mantid_browse_characterization_button.setText(_translate("MainWindow", "Browse Characterization ...", None))
        self.mantid_characterization_value.setText(_translate("MainWindow", "N/A", None))
        self.label_9.setText(_translate("MainWindow", "Number of Bins:", None))
        self.mantid_number_of_bins.setText(_translate("MainWindow", "-6000", None))
        self.label_7.setText(_translate("MainWindow", "(\"-\" for log binning)", None))
        self.label_23.setText(_translate("MainWindow", "Poly. degree", None))
        self.q_range_group_box.setTitle(_translate("MainWindow", "Q range", None))
        self.label.setText(_translate("MainWindow", "Qmin", None))
        self.q_range_min.setText(_translate("MainWindow", "0.2", None))
        self.label_2.setText(_translate("MainWindow", "Qmax", None))
        self.q_range_max.setText(_translate("MainWindow", "31.4", None))
        self.pushButton.setText(_translate("MainWindow", "Reset", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Crop Wavelength", None))
        self.label_15.setText(_translate("MainWindow", "Min", None))
        self.mantid_min_crop_wavelength.setText(_translate("MainWindow", ".1", None))
        self.label_16.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&#8491;</p></body></html>", None))
        self.label_14.setText(_translate("MainWindow", "Max", None))
        self.mantid_max_crop_wavelength.setText(_translate("MainWindow", "2.9", None))
        self.label_13.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&#8491;</p></body></html>", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Post-Processing", None))
        self.label_24.setText(_translate("MainWindow", "Poly. degree", None))

